"""Configuration for Archie IAM Role template."""
from typing import Optional, List, Dict, Any


class ArchieRoleConfig:
    """
    Configuration for Archie IAM Role template.
    
    Handles configuration for creating a cross-account IAM role
    that Archie can assume to deploy infrastructure.
    """
    
    def __init__(self, raw_config: Dict[str, Any]):
        self.raw_config = raw_config
        # Check parameters.aws first, fall back to parameters directly
        params = self.raw_config.get('parameters', {})
        self.parameters = params.get('aws', {}) or params

        # Core attributes
        self.project_name = (
            self.get_parameter('project_name') or
            self.get_parameter('projectName') or
            self.raw_config.get('projectName') or
            self.raw_config.get('project_name', 'archie-role')
        )
        self.environment = self.raw_config.get('environment', 'nonprod')
        self.region = self.raw_config.get('region', 'us-east-1')
        self.tags = self.raw_config.get('tags', {})
    
    def get_parameter(self, key: str, default: Any = None) -> Any:
        """Get a parameter from the configuration."""
        return self.parameters.get(key, default)
    
    @property
    def role_name(self) -> Optional[str]:
        """Custom role name (optional, will be auto-generated if not provided)"""
        return (
            self.get_parameter('role_name') or 
            self.get_parameter('roleName')
        )
    
    @property
    def archie_account_id(self) -> str:
        """Archie's AWS account ID that will assume this role"""
        return (
            self.get_parameter('archie_account_id') or 
            self.get_parameter('archieAccountId', '416851285955')
        )
    
    @property
    def external_id(self) -> Optional[str]:
        """External ID for additional security when assuming the role"""
        return (
            self.get_parameter('external_id') or 
            self.get_parameter('externalId')
        )
    
    @classmethod
    def get_config_schema(cls) -> Dict[str, Any]:
        """Get configuration schema for the UI."""
        return {
            "type": "object",
            "properties": {
                "essentials_header": {
                    "type": "separator",
                    "title": "Template Essentials",
                    "group": "Essentials",
                    "isEssential": True,
                    "order": 0
                },
                "project_name": {
                    "type": "string",
                    "title": "Project Name",
                    "description": "Unique name for this deployment (lowercase, no spaces)",
                    "default": "archie-role",
                    "group": "Essentials",
                    "isEssential": True,
                    "order": 1
                },
                "externalId": {
                    "type": "string",
                    "title": "External ID",
                    "description": "Unique security identifier generated by Archie",
                    "default": "f727e356-8035-4aa6-b507-25a1e5656b56",
                    "readOnly": True,
                    "group": "Essentials",
                    "isEssential": True,
                    "order": 2
                },
                "archieAccountId": {
                    "type": "string",
                    "title": "Archie Account ID",
                    "description": "The AWS Account ID of the Archie platform",
                    "default": "416851285955",
                    "readOnly": True,
                    "group": "Essentials",
                    "isEssential": True,
                    "order": 3
                },
                "security_banner": {
                    "type": "info",
                    "title": "Secure Cross-Account Trust",
                    "description": "The External ID and Account ID are used to establish a secure trust relationship. This prevents \"confused deputy\" attacks by ensuring Archie only assumes this role when specifically authorized for your unique integration.",
                    "group": "Essentials",
                    "isEssential": True,
                    "order": 4
                },
                "policy_preview": {
                    "type": "info",
                    "title": "ReadOnly Policy (Included)",
                    "description": "Archie deployments begin with Read-Only permissions. You will need to manually elevate this role's permissions in your AWS Console after the connection is established to enable infrastructure creation.",
                    "group": "Essentials",
                    "isEssential": True,
                    "is_essential": True,
                    "order": 5
                },
                "policy_document": {
                    "type": "syntax",
                    "title": "Policy Document",
                    "description": "JSON representation of the ReadOnly IAM policy",
                    "default": '{\n  "Version": "2012-10-17",\n  "Statement": [\n    {\n      "Effect": "Allow",\n      "Action": [\n        "ec2:Describe*",\n        "s3:List*",\n        "s3:Get*",\n        "rds:Describe*",\n        "elasticloadbalancing:Describe*",\n        "autoscaling:Describe*",\n        "cloudwatch:Describe*",\n        "cloudwatch:Get*",\n        "cloudwatch:List*",\n        "logs:Describe*",\n        "logs:Get*",\n        "logs:List*",\n        "iam:List*",\n        "iam:Get*",\n        "sns:List*",\n        "sns:Get*",\n        "sqs:List*",\n        "sqs:Get*",\n        "route53:List*",\n        "route53:Get*"\n      ],\n      "Resource": "*"\n    }\n  ]\n}',
                    "group": "Essentials",
                    "isEssential": True,
                    "is_essential": True,
                    "order": 6
                },
                "team_name": {
                    "type": "string",
                    "default": "",
                    "title": "Team Name",
                    "description": "Team that owns this resource",
                    "order": 50,
                    "group": "Tags",
                },
            },
            "required": ["project_name"]
        }
